version: "3.8"
services:
  database_mysql:
    container_name: db-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: manager_secret
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: order_manager
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/src/main/resources/sql_scripts/schema_with_data.sql:/docker-entrypoint-initdb.d/set.sql
    restart: always
    networks:
      - oder_manager_service_network
  oder_manager_service:
    container_name: oder-manager-service
    build: .
    environment:
      MYSQL_USER: manager_secret
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: order_manager
      API_ADDRESS_DATABASE: db-mysql
    ports:
      - "8080:8080"
    networks:
      - oder_manager_service_network
    depends_on:
      - database_mysql

networks:
  oder_manager_service_network: